### ISSUE TITLE
Saga argument must be a Generator function

### ISSUE THREAD

**Issue by sagarpatel8384** [bmealhouse/next-redux-saga#16]
I'm getting the following error when try to run my application with next-redux-saga:

```
redux-saga error: uncaught at check
runSaga(storeInterface, saga, ...args): saga argument must be a Generator function!
{ Error: runSaga(storeInterface, saga, ...args): saga argument must be a Generator function!
    at check (/Users/sapatel/Projects/teacher/teacher-app-client/node_modules/redux-saga/lib/internal/utils.js:45:11)
    at runSaga (/Users/sapatel/Projects/teacher/teacher-app-client/node_modules/redux-saga/lib/internal/runSaga.js:31:22)
    at Object.store.runSagaTask (/Users/sapatel/Projects/teacher/teacher-app-client/.next/server/bundles/pages/_app.js:174:37)
    at configureStore (/Users/sapatel/Projects/teacher/teacher-app-client/.next/server/bundles/pages/_app.js:177:9)
    at createStore (../src/index.js:21:30)
    at initStore (../src/index.js:30:25)
    at Function._callee$ (../src/index.js:65:26)
    at tryCatch (/Users/sapatel/Projects/teacher/teacher-app-client/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/sapatel/Projects/teacher/teacher-app-client/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/sapatel/Projects/teacher/teacher-app-client/node_modules/regenerator-runtime/runtime.js:114:21) sourceMapsApplied: true }
```

**Here is my rootSaga file**

```
import homeSagas from 'src/redux/sagas/homeSagas';
import { all } from 'redux-saga/effects';

// Root Saga - Generator Function
export default function* rootSaga() {
  yield all([
    ...homeSagas,
  ]);
}
```

**Here is my homeSagas file**

```
import { call, put, takeLatest } from 'redux-saga/effects';
import {
  HOME_LOADING,
  HOME_REQUEST,
  HOME_SUCCESS,
  HOME_ERROR,
} from 'src/redux/actions/actionTypes';
import { getHomeData } from 'src/api/home.api';

// Worker Saga - getHomeData - API Request
function* getHomeDataAsync(action) {
  try {
    yield put({
      type: HOME_LOADING,
      homeDataLoading: true,
    });
    yield call(getHomeData, action.payload);
    yield put({
      type: HOME_SUCCESS,
      homeDataLoading: false,
    });
  } catch (error) {
    yield put({
      type: HOME_ERROR,
      homeDataLoading: false,
      error,
    });
  }
}

// Watcher Saga
export default [
  takeLatest(HOME_REQUEST, getHomeDataAsync),
];
```

**Here is my store.js file**

```
import { createStore, applyMiddleware } from 'redux';
import createSagaMiddleware from 'redux-saga';
import rootReducer from 'src/redux/reducers';
import rootSaga from 'src/redux/sagas';
import logger from 'redux-logger';

const sagaMiddleware = createSagaMiddleware();

const configureStore = (initialState) => {
  const store = createStore(
    rootReducer,
    initialState,
    applyMiddleware(logger, sagaMiddleware),
  );

  store.runSagaTask = () => {
    store.sagaTask = sagaMiddleware.run(rootSaga);
  };

  store.runSagaTask();
  return store;
};

export default configureStore;
```

**And finally, here is my _app.js file**

```
import React from 'react';
import { Provider } from 'react-redux';
import App, { Container } from 'next/app';
import withRedux from 'next-redux-wrapper';
import withReduxSaga from 'next-redux-saga';
import configureStore from 'src/store';

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    return {
      pageProps: (Component.getInitialProps ? await Component.getInitialProps(ctx) : {}),
    };
  }

  render() {
    const { Component, pageProps, store } = this.props;
    return (
      <Container>
        <Provider store={store}>
          <Component {...pageProps} />
        </Provider>
      </Container>
    );
  }
}

export default withRedux(configureStore)(withReduxSaga(MyApp));
```
I've tried everything. Not sure where I'm going wrong here.

**Comment by sagarpatel8384** [comment]
I've been spinning my wheels on this for a while now with no real results. Any thoughts?

**Comment by bmealhouse** [comment]
@sagarpatel8384 - I looked at this briefly and I'm not able to reproduce.

I copied/pasted your code directly into a new project and everything is working fine for me. Take a look here: https://github.com/bmealhouse/nrs-issue-16

**Comment by sagarpatel8384** [comment]
Strange. I'll give it a shot building it from the ground up and report back. Possibly caused by a another dependency. Thanks

**Comment by sagarpatel8384** [comment]
Thanks, @bmealhouse. I used your version and everything seems to work fine now (even after I updated your code to my directory structure). Really odd but works now. Thanks.
