### ISSUE TITLE
TypeError: Cannot call a class as a function after upgraded to 4.0.1

### ISSUE THREAD

**Issue by fangqiao** [bmealhouse/next-redux-saga#50]
My nextjs/redux-saga app works well when I use next-redux-saga 3.0.0.
I upgraded it to 4.0.1, then this problem occured:

```
    at _classCallCheck (/home/fqye/projects/mashixiong/website/node_modules/next-redux-saga/dist/next-redux-saga.umd.js:48:13)
    at WrappedComponent (/home/fqye/projects/mashixiong/website/node_modules/next-redux-saga/dist/next-redux-saga.umd.js:137:9)
    at Module../src/components/presentation/UserCenter.tsx (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:3167:3)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
    at Module../src/reducers/userCenter.reducers.ts (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:5989:93)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
    at Module../src/reducers/root.reducers.ts (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:5829:78)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
    at Module../src/store/root.store.ts (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:7568:81)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
    at Module../src/components/connected/App/App.tsx (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:1759:76)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
    at Module../pages/_app.tsx (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:1407:91)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
    at Object.0 (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:7615:18)
    at __webpack_require__ (/home/fqye/projects/mashixiong/website/dist/server/static/development/pages/_app.js:23:31)
```

My code for connecting custom app to redux:
```
export default withRedux(createStore)(
  withReduxSaga(Application)
)
```
and creating store:

```
import { applyMiddleware, compose, createStore, Store } from "redux";
import createSagaMiddleware, { Task } from "redux-saga";

import { isServer } from "../helpers/dom";
import rootReducer from "../reducers/root.reducers";
import rootSaga from "../sagas/root.sagas";

type TStore = Store & {
  sagaTask?: Task;
  runSagaTask?: () => void;
};

export default (initialState = {}) => {
  // Environment
  const hasGA = !isServer() && typeof window.dataLayer !== "undefined";
  const hasMaps =
    !isServer() &&
    typeof window.google !== "undefined" &&
    typeof window.google.maps !== "undefined";
  const isDev = process.env.NODE_ENV === "development";

  // Middleware
  const sagaMiddleware = createSagaMiddleware();
  const middleware = [sagaMiddleware];

  // Redux devtools
  let composeEnhancers = compose;
  if (
    !isServer() &&
    isDev &&
    typeof window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ === "function"
  ) {
    composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;
  }

  // Redux store

  const store: TStore = createStore(
    rootReducer,
    initialState,

    composeEnhancers(applyMiddleware(...middleware))
  );

  store.runSagaTask = () => {
    store.sagaTask = sagaMiddleware.run(rootSaga, store.dispatch);
  };
  store.runSagaTask();


  return store;
};

```

Advice please. Thanks...

**Comment by bbortt** [comment]
Hi @fangqiao
Can you share the code for your `Application` as well, please?

**Comment by fangqiao** [comment]
@bbortt 
Sorry can't share whole code base as it is a quite serous project to alive soon.
Here is a simplified App.tsx code which still has the problem:

```
import * as React from 'react'

import withReduxSaga from 'next-redux-saga'
import withRedux from 'next-redux-wrapper'
import App, { AppComponentProps, Container } from 'next/app'
import { NextDocumentContext as Context } from 'next/document'
import { addLocaleData, IntlProvider } from 'react-intl'
import { Provider } from 'react-redux'
import { Store } from 'redux'
import createStore from '../../../store/root.store'

import { isServer } from '../../../helpers/dom'
import Shell from '../Shell/Shell'

import { END } from 'redux-saga'

// tslint:disable:no-submodule-imports
import en from 'react-intl/locale-data/en'
import chinese from 'react-intl/locale-data/zh'

// tslint:enable:no-submodule-imports

addLocaleData([...en, ...chinese])

type NextPageComponent = React.ComponentType<any> & {
  getInitialProps: (props: any) => any
}

interface IProps extends AppComponentProps {
  Component: NextPageComponent
  ctx: Context & { store: any }
  intlProps: {
    locale: string
    intlMessages: {}
    initialNow: Date
  }
  pageProps: {}
  store: Store<any>
}

const getIntlProps = (ctx: Context) => {
  const requestProps = isServer()
    ? ctx.req
    : window.__NEXT_DATA__.props.initialProps.intlProps
  const { locale, intlMessages } = requestProps

  return {
    initialNow: Date.now(),
    intlMessages: intlMessages || {},
    locale: locale || 'zh-CN'
  }
}

class Application extends App {
  public static async getInitialProps({ ctx, Component }: IProps) {

    if( isServer() ) {
      ctx.store.dispatch(END)
      await ctx.store.sagaTask.toPromise()
    }

  }

  public componentWillMount() {
    routes.Router.onRouteChangeStart = this.onRouteChangeStart
    routes.Router.onRouteChangeComplete = this.onRouteChangeComplete
    routes.Router.onRouteChangeError = this.onRouteChangeError
  }

  public componentDidMount() {
    if (!isServer()) {
      const { store } = this.props as IProps
      store.dispatch(actions.setCurrentRoute(routes.Router.route))
    }
  }

  public render() {
    const { Component, intlProps, pageProps, store } = this.props as IProps

    return (
      <Container>
        <Provider store={store}>
          <IntlProvider
            initialNow={intlProps.initialNow}
            messages={intlProps.intlMessages}
            locale={intlProps.locale}
          >
            <Shell>
              <Component {...pageProps} />
            </Shell>
          </IntlProvider>
        </Provider>
      </Container>
    )
  }

  private onRouteChangeStart = (path: string) => {
    const { store } = this.props as IProps

    store.dispatch(actions.changeRoute.started(path))
  }

  private onRouteChangeComplete = (path: string) => {
    const { store } = this.props as IProps

    store.dispatch(actions.changeRoute.done({ params: path }))
  }

  private onRouteChangeError = (error: Error, path: string) => {
    const { store } = this.props as IProps

    store.dispatch(
      actions.changeRoute.failed({
        error: {
          message: error.toString(),
          status: 500
        },
        params: path
      })
    )
  }
}

export default withRedux(createStore)(
  withReduxSaga({ async: true })(Application)
)

```

**Comment by bbortt** [comment]
This part `{ async: true }` does no longer exist. Asynchronous ist the one and only way to go now. Maybe this causes the problem. I can try to recreate a similar application this evening. Maybe you will have to help me a little bit ;)

**Comment by fangqiao** [comment]
I just tested with 
```
export default withRedux(createStore)(
  withReduxSaga(Application)
)
```
Still same error.
Sure I am happy to help.

**Comment by bbortt** [comment]
Closing this due to inactivity.
