### ISSUE TITLE
Cannot read property 'toPromise' of undefined

### ISSUE THREAD

**Issue by Arjun-Aggarwal** [bmealhouse/next-redux-saga#55]
I am trying to use redux-saga with next.js for the first time. For this, I have created a simple app. However, after following the example given here: https://github.com/zeit/next.js/blob/canary/examples/with-redux-saga/pages/_app.js
I am getting the error mentioned above. Here is the complete stack trace: 
```
TypeError: Cannot read property 'toPromise' of undefined
    at Function._callee$ (/Users/arjunaggarwal/Documents/GitHub/next-tutorial/node_modules/next-redux-saga/dist/next-redux-saga.umd.js:181:43)
    at tryCatch (/Users/arjunaggarwal/Documents/GitHub/next-tutorial/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/arjunaggarwal/Documents/GitHub/next-tutorial/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/arjunaggarwal/Documents/GitHub/next-tutorial/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/arjunaggarwal/Documents/GitHub/next-tutorial/node_modules/next-redux-saga/dist/next-redux-saga.umd.js:12:26)
    at _next (/Users/arjunaggarwal/Documents/GitHub/next-tutorial/node_modules/next-redux-saga/dist/next-redux-saga.umd.js:34:11)
```
My code is available on the following repo: 
https://github.com/Arjun-Aggarwal/next-trial
Is this my mistake or a bug with the library?  Please help.

**Comment by bbortt** [comment]
I think you missed the task assignment in `createStore.js` respectively your `store.js`..
```
- sagaMiddleware.run(rootSaga)
+ store.sagaTask = sagaMiddleware.run(rootSaga)
```
It is required by [`next-redux-saga`](https://github.com/bmealhouse/next-redux-saga/blob/master/index.js) on line 22. With this your example works fine ;)
