### ISSUE TITLE
Error: It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function.

### ISSUE THREAD

**Issue by ElijahKaftanov** [bmealhouse/next-redux-saga#58]
Hello there. I'm trying to use redux-saga in my project from example, but every second iteration redux throws an exception
condition from redux.js:72:11 triggered like: true && true || true && false

Error: It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function.
at createStore (/path-to-project/node_modules/redux/lib/redux.js:72:11)
at configureStore (/path-to-project/.next/server/static/development/pages/_app.js:959:74)
at createStore (/path-to-project/node_modules/next-redux-wrapper/lib/index.js:95:20)
at initStore (/path-to-project/node_modules/next-redux-wrapper/lib/index.js:98:20)
at new WrappedApp (/path-to-project/node_modules/next-redux-wrapper/lib/index.js:112:31)
at processChild (/path-to-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3048:14)
at resolve (/path-to-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:5)
at ReactDOMServerRenderer.render (/path-to-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:22)
at ReactDOMServerRenderer.read (/path-to-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
at renderToString (/path-to-project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
at render (/path-to-project/node_modules/next-server/dist/server/render.js:80:16)
at renderPage (/path-to-project/node_modules/next-server/dist/server/render.js:237:20)
at /path-to-project/.next/server/static/development/pages/_document.js:437:17
at Generator.next (<anonymous>)
  at asyncGeneratorStep (/path-to-project/.next/server/static/development/pages/_document.js:206:24)
  at _next (/path-to-project/.next/server/static/development/pages/_document.js:228:9)

**Comment by bbortt** [comment]
Hi @ElijahKaftanov 
I need a bit of code in order to help you.. at least the `configureStore.js`. Or a link to your repo would work as well.
Br, Timon

**Comment by ElijahKaftanov** [comment]
found it out: my fault was I passed into the initial state createReducer function instead of calling it :expressionless:

**Comment by bbortt** [comment]
@ElijahKaftanov glad you made it. issue resolved.
